#! /bin/bash

MEDIA=$HOME/src/michaux/catalogue/media
PIVOT=$MEDIA/CACHE/pivot
cd ${MEDIA}/images
[ ! -d $PIVOT ] && mkdir $PIVOT

for i in *.*
do 
    base=${i%.*}
    d=$MEDIA/CACHE/images/images/${base}
    if [ ! -f "$PIVOT/$base.dzi" -a -d "$d" ]
    then 
        echo "Processing $i"
        fname=$(ls -S "$d" | head -1)
        $HOME/src/michaux/deepzoom.py/deepzoom.py --tile_size=254 --tile_overlap=1 --square --tile_format=jpg --destination=$PIVOT/${i%.*}.dzi  "$d/$fname"
    fi
done
